version: '3'

services:
  fluentd:
    image: fluent/fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ${PWD}/fluentd/log:/fluentd/log
      - ${PWD}/fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    depends_on:
      - es

volumes:
  es-data: